config/routes.rb
Rails.application.routes.draw do

  resources :topics, except: [:edit, :update]

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  root 'home#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, presence: true, on: :create, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:sign_in][:email])
    if user && user.authenticate(params[:sign_in][:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Invalid email & password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      flash[:notice] = "Topic created"
      redirect_to topics_path
    else
      flash.now[:alert] = "Topic could not be saved, try again"
      render :new
    end
  end

  def new
    @topic = Topic.new
  end

  def destroy
  end

  def show
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Super Forum', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li id="user-email"> <%= current_user.email %></li>
          <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <section>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </section>

</body>
</html>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="header-with-button">
      <h1>Topics</h1>
      <%= link_to "Add Topic", new_topic_path, class: "btn btn-default btn-success" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class='data-table'>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% @topics.each do |topic| %>
          <tr>
            <td><%= topic.title %></td>
            <td><%= topic.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
      
    </div>
    

  </div>  
</div>

app/views/topics/new.html.erb
<h1>Add New Topic</h1>
<div class="row">
  <div class="col-md-4">
    <%= simple_form_for @topic do |f| %>
      <%= f.input :title %>
      <%= f.input :body %>
      <%= f.button :submit %>
    <% end %>  
  </div>
</div>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>